name: RPT Action

on:
    workflow_dispatch:
        inputs:
            productpath:
                description: 'Product Path'
                required: false
            imshared:
                description: 'IMShared Location'
                required: false
            workspace:
                description: 'Workspace'
                required: true
            project:
                description: 'Project'
                required: true
            suite:
                description: 'Test Suite Name'
                required: true

jobs:

    WebUI-Action:
        runs-on: self-hosted
        name: Execute RPT Test
        steps:
         - name: RPT Action
           uses: SonaHJ/RPTAction@RPT_Release
           with:
            productpath: '${{ github.event.inputs.productpath }}'
            imshared: '${{ github.event.inputs.imshared }}'
            workspace: '${{ github.event.inputs.workspace }}'
            project: '${{ github.event.inputs.project }}'
            suite: '${{ github.event.inputs.suite }}'
